/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as ProjectsScribbleUiRouteImport } from './routes/projects/scribble-ui'
import { Route as ProjectsScribbleRouteImport } from './routes/projects/scribble'
import { Route as ProjectsContextLayerRouteImport } from './routes/projects/context-layer'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as ApiRSplatRouteImport } from './routes/api/r/$'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsScribbleUiRoute = ProjectsScribbleUiRouteImport.update({
  id: '/projects/scribble-ui',
  path: '/projects/scribble-ui',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsScribbleRoute = ProjectsScribbleRouteImport.update({
  id: '/projects/scribble',
  path: '/projects/scribble',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsContextLayerRoute = ProjectsContextLayerRouteImport.update({
  id: '/projects/context-layer',
  path: '/projects/context-layer',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRSplatRoute = ApiRSplatRouteImport.update({
  id: '/api/r/$',
  path: '/api/r/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/projects/context-layer': typeof ProjectsContextLayerRoute
  '/projects/scribble': typeof ProjectsScribbleRoute
  '/projects/scribble-ui': typeof ProjectsScribbleUiRoute
  '/blog': typeof BlogIndexRoute
  '/api/r/$': typeof ApiRSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/projects/context-layer': typeof ProjectsContextLayerRoute
  '/projects/scribble': typeof ProjectsScribbleRoute
  '/projects/scribble-ui': typeof ProjectsScribbleUiRoute
  '/blog': typeof BlogIndexRoute
  '/api/r/$': typeof ApiRSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/projects/context-layer': typeof ProjectsContextLayerRoute
  '/projects/scribble': typeof ProjectsScribbleRoute
  '/projects/scribble-ui': typeof ProjectsScribbleUiRoute
  '/blog/': typeof BlogIndexRoute
  '/api/r/$': typeof ApiRSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog/$slug'
    | '/projects/context-layer'
    | '/projects/scribble'
    | '/projects/scribble-ui'
    | '/blog'
    | '/api/r/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog/$slug'
    | '/projects/context-layer'
    | '/projects/scribble'
    | '/projects/scribble-ui'
    | '/blog'
    | '/api/r/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog/$slug'
    | '/projects/context-layer'
    | '/projects/scribble'
    | '/projects/scribble-ui'
    | '/blog/'
    | '/api/r/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ProjectsContextLayerRoute: typeof ProjectsContextLayerRoute
  ProjectsScribbleRoute: typeof ProjectsScribbleRoute
  ProjectsScribbleUiRoute: typeof ProjectsScribbleUiRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiRSplatRoute: typeof ApiRSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/scribble-ui': {
      id: '/projects/scribble-ui'
      path: '/projects/scribble-ui'
      fullPath: '/projects/scribble-ui'
      preLoaderRoute: typeof ProjectsScribbleUiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/scribble': {
      id: '/projects/scribble'
      path: '/projects/scribble'
      fullPath: '/projects/scribble'
      preLoaderRoute: typeof ProjectsScribbleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/context-layer': {
      id: '/projects/context-layer'
      path: '/projects/context-layer'
      fullPath: '/projects/context-layer'
      preLoaderRoute: typeof ProjectsContextLayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/r/$': {
      id: '/api/r/$'
      path: '/api/r/$'
      fullPath: '/api/r/$'
      preLoaderRoute: typeof ApiRSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogSlugRoute: BlogSlugRoute,
  ProjectsContextLayerRoute: ProjectsContextLayerRoute,
  ProjectsScribbleRoute: ProjectsScribbleRoute,
  ProjectsScribbleUiRoute: ProjectsScribbleUiRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiRSplatRoute: ApiRSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
